AWSTemplateFormatVersion: "2010-09-09"

Description:
  CloudFormation template primitive which creates an AWS Simple AD Directory Service.

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: Directory Service Configuration
        Parameters:
          - Description
          - CreateAlias 
          - VpcId
          - EnableSso
          - Name
          - ShortName
          - SsmSimpleAdPassName
          - SsmVersion
          - Size
          - SubnetId1
          - SubnetId2

Parameters:
  Description:
    Type: String
    Default: A description of the directory.
  CreateAlias:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  VpcId:
    Description: Deploy to which VPC
    Type: AWS::EC2::VPC::Id
  EnableSso:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  Name:
    Type: String
    Default: DNSName
  ShortName:
    Type: String
    Default: ShortName
  SsmSimpleAdPassName:
    Description: The SSM secure parameter name which houses the directory password
    Type: String
  SsmVersion:
    Description: The SSM secure parameter name version to use
    Type: Number
  Size:
    Type: String
    Default: Small
    AllowedValues:
      - Small
      - Large
  SubnetId1:
    Description: Subnet 1
    Type: AWS::EC2::Subnet::Id
  SubnetId2:
    Description: Subnet 2
    Type: AWS::EC2::Subnet::Id
Resources:
  MyDirectory:
    Type: AWS::DirectoryService::SimpleAD
    Properties:
      Name: !Ref Name
      ShortName: !Ref ShortName
      Password: !Sub '{{resolve:ssm-secure:${SsmSimpleAdPassName}:${SsmVersion}}}'
      Size: !Ref Size
      VpcSettings:
        SubnetIds:
          - !Ref SubnetId1
          - !Ref SubnetId2
        VpcId: !Ref VpcId

Outputs:
  MyDirectoryId:
    Description: The ID of the directory
    Value: !Ref MyDirectory
    Export:
      Name: !Sub ${AWS::StackName}-${ShortName}-SIMPLEADID
